/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-29 07:14:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("/* html,\r\n");
      out.write("  button,\r\n");
      out.write("  input,\r\n");
      out.write("  select,\r\n");
      out.write("  textarea {\r\n");
      out.write("    font-family: \"Noto Sans\", \"malgun gothic\", AppleGothic, dotum, sans-serif;\r\n");
      out.write("  } */\r\n");
      out.write("nav {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	min-width: 1050px;\r\n");
      out.write("	letter-spacing: -0.3px;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	box-shadow: rgba(0, 0, 0, 0.07) 0px 3px 4px 0px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	/* position: fixed; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-top {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 1050px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	margin: 0px auto;\r\n");
      out.write("	letter-spacing: -0.3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-login {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 0px;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	z-index: 20;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-size: 11.3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-login {\r\n");
      out.write("	display: block;\r\n");
      out.write("	/* color: rgb(95, 0, 128); */\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	padding: 3px 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-login-down {\r\n");
      out.write("	width: 8px;\r\n");
      out.write("	height: 5px;\r\n");
      out.write("	background-image:\r\n");
      out.write("		url(\"https://res.kurly.com/pc/ico/1908/ico_down_16x10.png\");\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center center;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	/* margin-left: 3px; */\r\n");
      out.write("	margin-bottom: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-headerMain {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 63px;\r\n");
      out.write("	padding-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-search {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	-webkit-box-pack: justify;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 325px;\r\n");
      out.write("	/* top: -55px; */\r\n");
      out.write("	width: 390px;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	padding-left: 14px;\r\n");
      out.write("	border: 1px solid rgb(95, 0, 128);\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	box-shadow: rgb(247, 247, 247) 0px 0px 0px 1px inset;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-search-input {\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	background-color: inherit;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	letter-spacing: -0.33px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-search-icon {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	bottom: 3px;\r\n");
      out.write("	background:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCAzNiAzNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgzNnYzNkgweiIvPgogICAgICAgIDxnIHN0cm9rZT0iIzVGMDA4MCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2Utd2lkdGg9IjEuNyI+CiAgICAgICAgICAgIDxwYXRoIGQ9Im0yNi4wODEgMjYuMDgxLTQuMTItNC4xMk0xNi40NjcgMjMuMzM0YTYuODY3IDYuODY3IDAgMSAwIDAtMTMuNzM0IDYuODY3IDYuODY3IDAgMCAwIDAgMTMuNzM0eiIvPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+Cg==\")\r\n");
      out.write("		0px 0px no-repeat;\r\n");
      out.write("	border: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main_txt {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: rgb(95, 0, 128);\r\n");
      out.write("	flex-shrink: 0;\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	line-height: 1.33;\r\n");
      out.write("	letter-spacing: normal;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-icon {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: -6px;\r\n");
      out.write("	/* top: -49px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-adr {\r\n");
      out.write("	width: 36px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	background:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCAzNiAzNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTM2IDM2SDBWMGgzNnoiLz4KICAgICAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSg4LjcgNikiIHN0cm9rZT0iIzMzMyIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIxLjciPgogICAgICAgICAgICA8cGF0aCBkPSJNOS4zMDYgMjRTMCAxNi41NDQgMCA5LjMwNmE5LjMwNiA5LjMwNiAwIDAgMSAxOC42MTIgMEMxOC42MTIgMTYuNTQ0IDkuMzA2IDI0IDkuMzA2IDI0eiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIi8+CiAgICAgICAgICAgIDxjaXJjbGUgc3Ryb2tlLWxpbmVjYXA9InNxdWFyZSIgY3g9IjkuMjEyIiBjeT0iOS4xMjMiIHI9IjIuNzg0Ii8+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4K\")\r\n");
      out.write("		50% 50% no-repeat;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-like {\r\n");
      out.write("	width: 36px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	background:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCAzNiAzNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0yOC45MjcgOC44OTNhNi40NiA2LjQ2IDAgMCAwLTkuMTM5IDBsLTEuODI5IDEuODI4LTEuODI3LTEuODI4YTYuNDYyIDYuNDYyIDAgMSAwLTkuMTQgOS4xMzhMOC44MiAxOS44Nmw4LjQzMiA4LjQzNGExIDEgMCAwIDAgMS40MTQgMGw4LjQzMy04LjQzNGgwbDEuODI4LTEuODI4YTYuNDYgNi40NiAwIDAgMCAwLTkuMTM4eiIgc3Ryb2tlPSIjMzMzIiBzdHJva2Utd2lkdGg9IjEuNyIgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIiBzdHJva2UtbGluZWNhcD0icm91bmQiLz4KPC9zdmc+Cg==\")\r\n");
      out.write("		50% 50% no-repeat;\r\n");
      out.write("	border: 0px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-like:hover {\r\n");
      out.write("	background-image:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCAzNiAzNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0yOC45MjcgOC44OTNhNi40NiA2LjQ2IDAgMCAwLTkuMTM5IDBsLTEuODI5IDEuODI4LTEuODI3LTEuODI4YTYuNDYyIDYuNDYyIDAgMSAwLTkuMTQgOS4xMzhMOC44MiAxOS44Nmw4LjQzMiA4LjQzNGExIDEgMCAwIDAgMS40MTQgMGw4LjQzMy04LjQzNGgwbDEuODI4LTEuODI4YTYuNDYgNi40NiAwIDAgMCAwLTkuMTM4eiIgc3Ryb2tlPSIjNWYwMDgwIiBzdHJva2Utd2lkdGg9IjEuNyIgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIiBzdHJva2UtbGluZWNhcD0icm91bmQiLz4KPC9zdmc+Cg==\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-cart {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 36px;\r\n");
      out.write("	height: 36px;\r\n");
      out.write("	background:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHZpZXdCb3g9IjAgMCAzNiAzNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTM2IDM2SDBWMGgzNnoiLz4KICAgICAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1LjE2NCA2LjU0NykiIHN0cm9rZT0iIzMzMyIgc3Ryb2tlLWxpbmVjYXA9InNxdWFyZSIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIxLjciPgogICAgICAgICAgICA8cGF0aCBkPSJtMjUuNjggMy42Ni0yLjcyIDExLjU3SDcuMzdMNC42NiAzLjY2eiIvPgogICAgICAgICAgICA8Y2lyY2xlIGN4PSIyMC41MiIgY3k9IjIwLjc4IiByPSIyLjE0Ii8+CiAgICAgICAgICAgIDxjaXJjbGUgY3g9IjkuODEiIGN5PSIyMC43OCIgcj0iMi4xNCIvPgogICAgICAgICAgICA8cGF0aCBkPSJNMCAwaDMuOGwxLjc2IDcuNSIvPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+Cg==\");\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border: 0px solid white;\r\n");
      out.write("	margin-left: 18px;\r\n");
      out.write("	margin-right: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-header {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-pack: justify;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	width: 1050px;\r\n");
      out.write("	height: 56px;\r\n");
      out.write("	margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-header-cg:hover>span:first-of-type {\r\n");
      out.write("	background:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTQiIHZpZXdCb3g9IjAgMCAxNiAxNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0wIDBoMTZ2MS43SDBWMHptMCA2LjE1aDE2djEuN0gwdi0xLjd6bTAgNi4xNWgxNlYxNEgwdi0xLjd6IiBmaWxsPSIjNUYwMDgwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==\")\r\n");
      out.write("		no-repeat 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-header-cg:hover>span:last-of-type {\r\n");
      out.write("	color: rgb(95, 0, 128);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-header-cg {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-header-cg-icon {\r\n");
      out.write("	width: 16px;\r\n");
      out.write("	height: 14px;\r\n");
      out.write("	margin-right: 14px;\r\n");
      out.write("	background:\r\n");
      out.write("		url(\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTQiIHZpZXdCb3g9IjAgMCAxNiAxNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0wIDBoMTZ2MS43SDBWMHptMCA2LjE1aDE2djEuN0gwdi0xLjd6bTAgNi4xNWgxNlYxNEgwdi0xLjd6IiBmaWxsPSIjMzMzIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==\")\r\n");
      out.write("		0px 0px/16px 14px no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-header-cg {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	line-height: 20px;\r\n");
      out.write("	letter-spacing: -1.5px;\r\n");
      out.write("	color: rgb(51, 51, 51);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-header-cg-sub {\r\n");
      out.write("	max-height: calc(95vh - 55px);\r\n");
      out.write("	min-height: 200px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	display: none;\r\n");
      out.write("	top: 46px;\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cg-sub-container {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 21;\r\n");
      out.write("	width: 249px;\r\n");
      out.write("	border: 1px solid rgb(221, 221, 221);\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	animation: 0s linear 0s 1 normal none running animation-w43n76;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cg-sub-ul {\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	width: 222px;\r\n");
      out.write("	height: 92%;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cg-sub-li {\r\n");
      out.write("	padding: 7px 0px 9px 14px;\r\n");
      out.write("	background-color: rgba(255, 255, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cg-sub-div {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	align-items: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cg-sub-img {\r\n");
      out.write("	flex: 0 1 0%;\r\n");
      out.write("	width: 24px;\r\n");
      out.write("	height: 24px;\r\n");
      out.write("	padding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav-header-ul {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	margin-left: -90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-header-li {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-pack: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("	padding-top: 3px;\r\n");
      out.write("	line-height: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-header-txt {\r\n");
      out.write("	height: fit-content;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: rgb(51, 51, 51);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#blank {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-align: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<div class=\"nav-top\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"nav-login\">\r\n");
      out.write("				<a class=\"nav-login\">회원가입</a> <a> | </a> <a class=\"nav-login\">로그인</a>\r\n");
      out.write("				<a> | </a> <a class=\"nav-login\" href=\"/product/searchProduct.do\"> 관리자페이지 \r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"nav-headerMain\">\r\n");
      out.write("				<img src=\"/images/KKURLY_LOGO2.png\" alt=\"Bootstrap\" width=\"120\"\r\n");
      out.write("					style=\"flex: 0 0 82px;\">\r\n");
      out.write("				<p id=\"main_txt\">마켓껄리</p>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"nav-search\">\r\n");
      out.write("					<input id=\"gnb_search\" class=\"nav-search-input\"\r\n");
      out.write("						placeholder=\"검색어를 입력해주세요\" required=\"\" value=\"\">\r\n");
      out.write("					<button id=\"submit\" class=\"nav-search-icon\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"nav-icon\">\r\n");
      out.write("					<div class=\"icon-adr\"></div>\r\n");
      out.write("					<button class=\"icon-like\"></button>\r\n");
      out.write("					<button class=\"icon-cart\"\r\n");
      out.write("						onclick=\"location.href='/cart/cartList.do'\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"nav-header\">\r\n");
      out.write("				<div id=\"nav-header-cg\">\r\n");
      out.write("					<span class=\"nav-header-cg-icon\"></span> <span\r\n");
      out.write("						class=\"nav-heager-cg\" id=\"nav-heager-cg\">카테고리</span>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"nav-header-cg-sub\" id=\"cg-sub\">\r\n");
      out.write("						<div width=\"0\" class=\"cg-sub-container\">\r\n");
      out.write("							<ul class=\"cg-sub-ul\">\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='/categori.do?CD=vet'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/1/4IYbd0CEWkokpqiN00CAL9cDC2Q7nT101TDEn0tF.png\"\r\n");
      out.write("											alt=\"채소\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">채소</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/2/DNXCcUaXoXakDOdHiGhIMCNUeUjJioG9EyeQ7RRX.png\"\r\n");
      out.write("											alt=\"과일\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">과일</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/3/fivaoZPBTeqaDswJUgr3k0xMV0von36Qb9qnn7ZZ.png\"\r\n");
      out.write("											alt=\"수산물\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">수산물</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/4/jj6zZg2sY94aytlc2k1udIAmWWvmUignR9VYaMcm.png\"\r\n");
      out.write("											alt=\"육류\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">육류</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/19/DeT1R9JFqxgxubAIJuFcbZPPbBu8DHUkFJmGZBlJ.png\"\r\n");
      out.write("											alt=\"반려동물\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">반려동물</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/6/kwat5Szmq0ONTpMd4hlbcGmCOBd3FsMPyTzWxKBb.png\"\r\n");
      out.write("											alt=\"간편식\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">간편식</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/12/UnO3V0GDnss8p37EKmTGvnF9SzeyzgyzC0O7Wh1R.png\"\r\n");
      out.write("											alt=\"주류\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">주류</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/8/bKllScRqF9gQ5q58LcmBfOOhgBrCOdVypPiRvQkL.png\"\r\n");
      out.write("											alt=\"음료\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">음료</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"cg-sub-li\">\r\n");
      out.write("									<div class=\"cg-sub-div\" onclick=\"location.href='#'\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://collection-image.kurly.com/site-category-groups/9/5qKRHLtIeBWLxUPa1g3koUhqsAkc39YjtMnyIXCJ.png\"\r\n");
      out.write("											alt=\"베이커리\" class=\"cg-sub-img\"><span class=\"cg-sub-span\">베이커리</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li width=\"0\" class=\"css-1xy9xh5 e1vs1ym85\"></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul id=\"nav-header-ul\">\r\n");
      out.write("					<li class=\"nav-header-li\"><span class=\"nav-header-txt\">신상품</span></li>\r\n");
      out.write("					<li class=\"nav-header-li\"><span class=\"nav-header-txt\">베스트</span></li>\r\n");
      out.write("					<li class=\"nav-header-li\"><span class=\"nav-header-txt\">특가/혜택</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<div id=\"blank\"></div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	document.getElementById(\"nav-header-cg\").addEventListener(\"mouseover\",\r\n");
      out.write("			function() {\r\n");
      out.write("				document.getElementById(\"cg-sub\").style.display = \"flex\";\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("	document.getElementById(\"nav-header-cg\").addEventListener(\"mouseleave\",\r\n");
      out.write("			function() {\r\n");
      out.write("				document.getElementById(\"cg-sub\").style.display = \"none\";\r\n");
      out.write("			});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
