/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-30 03:14:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainFooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#footer {\r\n");
      out.write("	width: 1110px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	padding-bottom: 60px;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	letter-spacing: -.2px;\r\n");
      out.write("}\r\n");
      out.write("#footer::after {\r\n");
      out.write("	display: block;\r\n");
      out.write("	content: '';\r\n");
      out.write("	clear: both;\r\n");
      out.write("}\r\n");
      out.write("#footer .inner_footer {\r\n");
      out.write("	/* overflow: hidden; */\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("#footer .inner_footer::after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	clear: both;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write(".inner_footer .cc_footer {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("}\r\n");
      out.write(".inner_footer .cc_tit {\r\n");
      out.write("	padding: 29px 0 2px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	line-height: 24px;\r\n");
      out.write("	margin-bottom: 0px\r\n");
      out.write("}\r\n");
      out.write(".inner_footer .cc_view {\r\n");
      out.write("	/* overflow: hidden; */\r\n");
      out.write("	padding-top: 12px;\r\n");
      out.write("}\r\n");
      out.write(".inner_footer .cc_view .tit {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("	margin-right: 16px;\r\n");
      out.write("}\r\n");
      out.write(".inner_footer .cc_call {\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".inner_footer .cc_call .tit {\r\n");
      out.write("	padding-top: 4px;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	line-height: 36px;\r\n");
      out.write("	letter-spacing: -.5px;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write(".cc_footer .list {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	line-height: 22px;\r\n");
      out.write("	letter-spacing: -.2px;\r\n");
      out.write("}\r\n");
      out.write(".cc_footer .list .etc {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	/* line-height: 22px; */\r\n");
      out.write("	letter-spacing: -.2px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".cc_footer .cc_kakao .tit, .cc_footer .cc_qna .tit {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	padding-top: 7px;\r\n");
      out.write("	margin-top: 3px;\r\n");
      out.write("	border: 1px solid #e3e3e3;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	line-height: 22px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".cc_footer .list dd {\r\n");
      out.write("	color: #999;\r\n");
      out.write("}\r\n");
      out.write("/* #footer right */\r\n");
      out.write("#footer .company_info {\r\n");
      out.write("	float: right;\r\n");
      out.write("	padding-top: 29px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	line-height: 20px;\r\n");
      out.write("}\r\n");
      out.write(".company_info .list {\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("	padding-left: 0px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".company_info .list li {\r\n");
      out.write("	float: left;\r\n");
      out.write("	padding-right: 16px;\r\n");
      out.write("}\r\n");
      out.write(".company_info .list .link {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	line-height: 18px;\r\n");
      out.write("	text-decoration-line: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".company_info .spec_info .bar {\r\n");
      out.write("	padding: 0 4px 0 3px;\r\n");
      out.write("}\r\n");
      out.write(".company_info .spec_info .link {\r\n");
      out.write("	color: #5f0080;\r\n");
      out.write("}\r\n");
      out.write(".company_info .spec_info .copy {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("	color: #949296;\r\n");
      out.write("	line-height: 22px;\r\n");
      out.write("	letter-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write(".spec_info .sns {\r\n");
      out.write("	float: left;\r\n");
      out.write("	padding-top: 16px;\r\n");
      out.write("	padding-left: 0px;\r\n");
      out.write("}\r\n");
      out.write(".sns li {\r\n");
      out.write("	float: left;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".sns .link_sns {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	width: 10px;\r\n");
      out.write("	height: 10px;\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("}\r\n");
      out.write(".sns .link_sns img {\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("#footer .link_footer {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	padding-top: 19px;\r\n");
      out.write("	letter-spacing: 0;\r\n");
      out.write("	border-top: 1px solid #eee;\r\n");
      out.write("}\r\n");
      out.write(".link_footer::after {\r\n");
      out.write("	display: block;\r\n");
      out.write("	content: '';\r\n");
      out.write("	clear: both;\r\n");
      out.write("}\r\n");
      out.write(".link_footer .authentication {\r\n");
      out.write("	float: left;\r\n");
      out.write("	padding-top: 3px;\r\n");
      out.write("}\r\n");
      out.write(".link_footer .authentication .mark {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 267px;\r\n");
      out.write("}\r\n");
      out.write(".link_footer .mark .logo {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 34px;\r\n");
      out.write("	height: 34px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write(".link_footer .mark .txt {\r\n");
      out.write("	float: left;\r\n");
      out.write("	padding-top: 1px;\r\n");
      out.write("	margin-top: 0px;\r\n");
      out.write("	font-size: 7px;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	line-height: 16px;\r\n");
      out.write("	letter-spacing: -.5px;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	width: 125px;\r\n");
      out.write("}\r\n");
      out.write("#footer .lguplus {\r\n");
      out.write("	width: 283px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".link_footer .lguplus .logo {\r\n");
      out.write("	width: 102px;\r\n");
      out.write("	height: 34px;\r\n");
      out.write("}\r\n");
      out.write("hr {\r\n");
      out.write("	opacity: 0.1;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div class=\"inner_footer\">\r\n");
      out.write("			<div class=\"cc_footer\">\r\n");
      out.write("				<!-- cc = company calls -->\r\n");
      out.write("				<h2 class=\"cc_tit\">고객행복센터</h2>\r\n");
      out.write("				<div class=\"cc_view cc_call\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<span class=\"tit\">1644-1107</span>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<dl class=\"list\">\r\n");
      out.write("						<dt>\r\n");
      out.write("							<br>\r\n");
      out.write("						</dt>\r\n");
      out.write("						<dd class=\"etc\">월-토요일 오전 7시 - 오후 6시</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"cc_view cc_kakao\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<a href=\"#\" class=\"tit\">카카오톡 문의</a>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<dl class=\"list\">\r\n");
      out.write("						<dt>365고객센터</dt>\r\n");
      out.write("						<dd>오전 7시 - 오후 7시</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"cc_view cc_qna\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<a href=\"#\" class=\"tit\">1:1 문의</a>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<dl class=\"list\">\r\n");
      out.write("						<dt>24시간 접수 가능</dt>\r\n");
      out.write("						<dd>고객센터 운영시간에 순차적으로 답변해드리겠습니다.</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"company_info\">\r\n");
      out.write("				<ul class=\"list\">\r\n");
      out.write("					<li><a href=\"#\" class=\"link\">컬리소개</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"link\">컬리소개영상</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"link\">인재채용</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"link\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"link\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"#\" class=\"link\">이용안내</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<div class=\"spec_info\">\r\n");
      out.write("					법인명 (상호) : 주식회사 껄리 <span class=\"bar\">I</span> 사업자등록번호 : 000-00-0000\r\n");
      out.write("					<a href=\"#\" class=\"link\">사업자정보확인</a><br> 통신판매업 : 제\r\n");
      out.write("					2018-서울강남-00000 호 <span class=\"bar\">I</span> 개인정보보호책임자 : 000 <br>\r\n");
      out.write("					주소 : 서울시 도산대로 16길 20, 이래빌딩 B1 ~ 4F 아님 <span class=\"bar\">I</span>\r\n");
      out.write("					대표이사 : 000 <br> 입점문의 : <a href=\"#\" class=\"link\">입점문의하기</a>\r\n");
      out.write("					제휴문의 : <a href=\"#\" class=\"link\">kkurly_fake@naver.com</a><br>\r\n");
      out.write("					채용문의 : <a href=\"#\" class=\"link\">kkurly_fake@naver.com</a><br>\r\n");
      out.write("					팩스 : 000 - 0000 - 0000 <span class=\"bar\">I</span> 이메일 : <a href=\"#\"\r\n");
      out.write("						class=\"link\">kkurly_fake@naver.com</a><br> <br> <strong\r\n");
      out.write("						class=\"copy\">© KURLY CORP. ALL RIGHTS RESERVED</strong>\r\n");
      out.write("					<ul class=\"sns\">\r\n");
      out.write("						<li><a href=\"#\" class=\"link_sns insta\" target=\"_blank\"> <img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_instagram.png\"\r\n");
      out.write("								alt=\"마켓컬리 인스타그램 바로가기\">\r\n");
      out.write("						</a> <!-- bg url 넣기 --></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"link_sns fb\" target=\"_blank\"> <img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_fb.png\"\r\n");
      out.write("								alt=\"마켓컬리 페이스북 바로가기\">\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"link_sns naver_blog\" target=\"_blank\">\r\n");
      out.write("								<img src=\"https://res.kurly.com/pc/ico/1810/ico_blog.png\"\r\n");
      out.write("								alt=\"마켓컬리 네이버블로그 바로가기\">\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"link_sns naver_post\" target=\"_blank\">\r\n");
      out.write("								<img src=\"https://res.kurly.com/pc/ico/1810/ico_naverpost.png\"\r\n");
      out.write("								alt=\"마켓컬리 포스트 바로가기\">\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"link_sns yt\" target=\"_blank\"> <img\r\n");
      out.write("								src=\"https://res.kurly.com/pc/ico/1810/ico_youtube.png\"\r\n");
      out.write("								alt=\"마켓컬리 유튜브 바로가기\">\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"link_footer\">\r\n");
      out.write("			<div class=\"authentication\">\r\n");
      out.write("				<a href=\"#\" class=\"mark\" target=\"_blank\"> <img\r\n");
      out.write("					src=\"https://res.kurly.com/pc/ico/2208/logo_isms.svg\" alt=\"isms 로고\"\r\n");
      out.write("					class=\"logo\">\r\n");
      out.write("					<p class=\"txt\">\r\n");
      out.write("						[인증범위] 마켓컬리 쇼핑몰 서비스 개발 · 운영<br> (심사받지 않은 물리적 인프라 제외)<br>\r\n");
      out.write("						[유효기간] 2019.04.01 ~ 2022.03.31\r\n");
      out.write("					</p>\r\n");
      out.write("				</a> <a href=\"#\" class=\"mark\" target=\"_blank\"> <img\r\n");
      out.write("					src=\"https://res.kurly.com/pc/ico/2001/logo_eprivacyplus.png\"\r\n");
      out.write("					alt=\"eprivacy plus 로고\" class=\"logo\">\r\n");
      out.write("					<p class=\"txt\">\r\n");
      out.write("						개인정보보호 우수 웹사이트 ·<br> 개인정보처리시스템 인증 없음(ePRIVACY PLUS)\r\n");
      out.write("					</p>\r\n");
      out.write("				</a> <a href=\"#\" class=\"lguplus mark\" target=\"_blank\"> <img\r\n");
      out.write("					src=\"https://res.kurly.com/pc/service/main/2009/logo_payments.png\"\r\n");
      out.write("					alt=\"payments 로고\" class=\"logo\">\r\n");
      out.write("					<p class=\"txt\">\r\n");
      out.write("						토스페이먼츠 구매안전(에스크로)<br> 서비스를 이용하실 수 없습니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</a> <a href=\"#\" class=\"mark\" target=\"_blank\"> <img\r\n");
      out.write("					src=\"https://res.kurly.com/pc/ico/2208/logo_wooriBank.svg\"\r\n");
      out.write("					alt=\"우리은행 로고\" class=\"logo\">\r\n");
      out.write("					<p class=\"txt\">\r\n");
      out.write("						고객님이 현금으로 결제한 금액에 대해 우리은행과<br> 채무지급보증 계약을 체결하여 안전거래를 보장하고<br>\r\n");
      out.write("						있지 않습니다.\r\n");
      out.write("					</p>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- id=\"footer\" -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
